/**
 * Change Task Orchestration — Deterministic Demo Seed
 *
 * Creates a rich demo dataset for Change Task orchestration and templates:
 * 1. One change template with mixed orchestration (parallel + serial + optional)
 * 2. One change record with the template applied
 * 3. Tasks in mixed states to demonstrate summary/readiness
 * 4. Dependency graph demonstrating serial/parallel patterns
 * 5. Traceability fields populated (autoGenerated, sourceTemplateId, templateTaskKey)
 *
 * IDEMPOTENCY: Every record is looked up by deterministic ID before insert.
 *              Re-runs log CREATED / REUSED per record. No duplicate explosion.
 *
 * DEPENDENCIES: seed:grc (tenant must exist)
 *
 * Usage:
 *   DEV:  npx ts-node -r tsconfig-paths/register src/scripts/seed-change-task-demo.ts
 *   PROD: node dist/scripts/seed-change-task-demo.js
 */

process.env.JOBS_ENABLED = 'false';

import { NestFactory } from '@nestjs/core';
import { DataSource } from 'typeorm';
import { AppModule } from '../app.module';
import { Tenant } from '../tenants/tenant.entity';
import {
  ItsmChange,
  ChangeType,
  ChangeState,
  ChangeRisk,
  ChangeApprovalStatus,
} from '../itsm/change/change.entity';
import { ItsmChangeTemplate } from '../itsm/change/template/change-template.entity';
import { ItsmChangeTemplateTask } from '../itsm/change/template/change-template-task.entity';
import { ItsmChangeTemplateDependency } from '../itsm/change/template/change-template-dependency.entity';
import {
  ItsmChangeTask,
  ChangeTaskStatus,
  ChangeTaskType,
  ChangeTaskPriority,
} from '../itsm/change/task/change-task.entity';
import { ItsmChangeTaskDependency } from '../itsm/change/task/change-task-dependency.entity';

// ============================================================================
// DETERMINISTIC IDS — prefix eeee to avoid collision with other seeds
// ============================================================================

const DEMO_TENANT_ID = '00000000-0000-0000-0000-000000000001';
const DEMO_ADMIN_ID = '00000000-0000-0000-0000-000000000002';

const ID = {
  // Template
  TEMPLATE: 'eeee0100-0000-0000-0000-000000000001',
  // Template tasks
  TT_PRE1: 'eeee0200-0000-0000-0000-000000000001',
  TT_PRE2: 'eeee0200-0000-0000-0000-000000000002',
  TT_IMPL1: 'eeee0200-0000-0000-0000-000000000003',
  TT_IMPL2: 'eeee0200-0000-0000-0000-000000000004',
  TT_VAL1: 'eeee0200-0000-0000-0000-000000000005',
  TT_VAL2: 'eeee0200-0000-0000-0000-000000000006',
  TT_BACKOUT: 'eeee0200-0000-0000-0000-000000000007',
  // Template dependencies
  TD_1: 'eeee0300-0000-0000-0000-000000000001',
  TD_2: 'eeee0300-0000-0000-0000-000000000002',
  TD_3: 'eeee0300-0000-0000-0000-000000000003',
  TD_4: 'eeee0300-0000-0000-0000-000000000004',
  TD_5: 'eeee0300-0000-0000-0000-000000000005',
  TD_6: 'eeee0300-0000-0000-0000-000000000006',
  // Change
  CHANGE: 'eeee0400-0000-0000-0000-000000000001',
  // Applied tasks (created from template)
  TASK_PRE1: 'eeee0500-0000-0000-0000-000000000001',
  TASK_PRE2: 'eeee0500-0000-0000-0000-000000000002',
  TASK_IMPL1: 'eeee0500-0000-0000-0000-000000000003',
  TASK_IMPL2: 'eeee0500-0000-0000-0000-000000000004',
  TASK_VAL1: 'eeee0500-0000-0000-0000-000000000005',
  TASK_VAL2: 'eeee0500-0000-0000-0000-000000000006',
  TASK_BACKOUT: 'eeee0500-0000-0000-0000-000000000007',
  // Applied dependencies
  DEP_1: 'eeee0600-0000-0000-0000-000000000001',
  DEP_2: 'eeee0600-0000-0000-0000-000000000002',
  DEP_3: 'eeee0600-0000-0000-0000-000000000003',
  DEP_4: 'eeee0600-0000-0000-0000-000000000004',
  DEP_5: 'eeee0600-0000-0000-0000-000000000005',
  DEP_6: 'eeee0600-0000-0000-0000-000000000006',
};

// ============================================================================
// HELPERS
// ============================================================================

type SeedAction = 'CREATED' | 'REUSED';

function logAction(action: SeedAction, entity: string, label: string): void {
  const icon = action === 'CREATED' ? '+' : '=';
  console.log(`   ${icon} ${action} ${entity}: ${label}`);
}

const NOW = new Date();
function hoursAgo(h: number): Date {
  return new Date(NOW.getTime() - h * 60 * 60 * 1000);
}

// ============================================================================
// MAIN
// ============================================================================

async function seedChangeTaskDemo(): Promise<void> {
  console.log('');
  console.log('='.repeat(70));
  console.log('  CHANGE TASK ORCHESTRATION — Deterministic Demo Seed');
  console.log('  Template: Standard Deployment (7 tasks, 6 dependencies)');
  console.log('  Change:   Database Platform Upgrade with applied template');
  console.log('='.repeat(70));
  console.log('');

  const app = await NestFactory.createApplicationContext(AppModule);
  const ds = app.get(DataSource);

  const stats = { created: 0, reused: 0 };
  function track(a: SeedAction): void {
    if (a === 'CREATED') stats.created++;
    else stats.reused++;
  }

  try {
    // ── Verify tenant ──
    console.log('LAYER 0: Verifying prerequisites...');
    const tenant = await ds
      .getRepository(Tenant)
      .findOne({ where: { id: DEMO_TENANT_ID } });
    if (!tenant) {
      console.error('  ERROR: Demo tenant not found. Run seed:grc first.');
      process.exit(1);
    }
    console.log(`  Tenant: ${tenant.name}`);
    console.log('');

    // ── LAYER 1: Change Template ──
    console.log('LAYER 1: Seeding Change Template...');
    const tmplRepo = ds.getRepository(ItsmChangeTemplate);
    let template = await tmplRepo.findOne({ where: { id: ID.TEMPLATE } });
    if (!template) {
      template = tmplRepo.create({
        id: ID.TEMPLATE,
        tenantId: DEMO_TENANT_ID,
        name: 'Standard Deployment Pack',
        code: 'STD_DEPLOY_V1',
        description:
          'Standard deployment template with parallel pre-checks, serial implementation, parallel validation, and optional backout.',
        isActive: true,
        isGlobal: false,
        version: 1,
        createdBy: DEMO_ADMIN_ID,
        isDeleted: false,
      });
      template = await tmplRepo.save(template);
      logAction('CREATED', 'Template', template.name);
      track('CREATED');
    } else {
      logAction('REUSED', 'Template', template.name);
      track('REUSED');
    }

    // ── LAYER 2: Template Tasks ──
    console.log('LAYER 2: Seeding Template Tasks (7)...');
    const ttRepo = ds.getRepository(ItsmChangeTemplateTask);

    const templateTasks = [
      {
        id: ID.TT_PRE1,
        taskKey: 'pre_check_1',
        title: 'Verify DB Backup Completed',
        taskType: 'PRE_CHECK',
        seq: 0,
        sort: 0,
        stage: 'Pre-Flight',
        blocking: true,
      },
      {
        id: ID.TT_PRE2,
        taskKey: 'pre_check_2',
        title: 'Validate Rollback Script',
        taskType: 'PRE_CHECK',
        seq: 1,
        sort: 1,
        stage: 'Pre-Flight',
        blocking: true,
      },
      {
        id: ID.TT_IMPL1,
        taskKey: 'implement_1',
        title: 'Run Database Migration',
        taskType: 'IMPLEMENTATION',
        seq: 2,
        sort: 2,
        stage: 'Execute',
        blocking: true,
      },
      {
        id: ID.TT_IMPL2,
        taskKey: 'implement_2',
        title: 'Update Application Config',
        taskType: 'IMPLEMENTATION',
        seq: 3,
        sort: 3,
        stage: 'Execute',
        blocking: true,
      },
      {
        id: ID.TT_VAL1,
        taskKey: 'validate_1',
        title: 'Run Integration Test Suite',
        taskType: 'VALIDATION',
        seq: 4,
        sort: 4,
        stage: 'Validate',
        blocking: true,
      },
      {
        id: ID.TT_VAL2,
        taskKey: 'validate_2',
        title: 'Verify Monitoring Dashboards',
        taskType: 'VALIDATION',
        seq: 5,
        sort: 5,
        stage: 'Validate',
        blocking: false,
      },
      {
        id: ID.TT_BACKOUT,
        taskKey: 'backout_prep',
        title: 'Prepare Backout Procedure',
        taskType: 'BACKOUT',
        seq: 6,
        sort: 6,
        stage: 'Backout',
        blocking: false,
      },
    ];

    for (const tt of templateTasks) {
      let existing = await ttRepo.findOne({ where: { id: tt.id } });
      if (!existing) {
        existing = ttRepo.create({
          id: tt.id,
          tenantId: DEMO_TENANT_ID,
          templateId: ID.TEMPLATE,
          taskKey: tt.taskKey,
          title: tt.title,
          description: null,
          taskType: tt.taskType,
          defaultStatus: ChangeTaskStatus.OPEN,
          defaultPriority: 'MEDIUM',
          sequenceOrder: tt.seq,
          isBlocking: tt.blocking,
          sortOrder: tt.sort,
          stageLabel: tt.stage,
          createdBy: DEMO_ADMIN_ID,
          isDeleted: false,
        } as Partial<ItsmChangeTemplateTask> as ItsmChangeTemplateTask);
        await ttRepo.save(existing);
        logAction('CREATED', 'TemplateTask', tt.title);
        track('CREATED');
      } else {
        logAction('REUSED', 'TemplateTask', tt.title);
        track('REUSED');
      }
    }

    // ── LAYER 3: Template Dependencies ──
    // Dependency graph:
    //   pre_check_1 ──┐
    //                  ├──> implement_1 ──> implement_2 ──┬──> validate_1
    //   pre_check_2 ──┘                                    └──> validate_2
    //   pre_check_1 ──> backout_prep (parallel, non-blocking)
    console.log('LAYER 3: Seeding Template Dependencies (6)...');
    const tdRepo = ds.getRepository(ItsmChangeTemplateDependency);

    const templateDeps = [
      { id: ID.TD_1, pred: 'pre_check_1', succ: 'implement_1' },
      { id: ID.TD_2, pred: 'pre_check_2', succ: 'implement_1' },
      { id: ID.TD_3, pred: 'implement_1', succ: 'implement_2' },
      { id: ID.TD_4, pred: 'implement_2', succ: 'validate_1' },
      { id: ID.TD_5, pred: 'implement_2', succ: 'validate_2' },
      { id: ID.TD_6, pred: 'pre_check_1', succ: 'backout_prep' },
    ];

    for (const td of templateDeps) {
      let existing = await tdRepo.findOne({ where: { id: td.id } });
      if (!existing) {
        existing = tdRepo.create({
          id: td.id,
          tenantId: DEMO_TENANT_ID,
          templateId: ID.TEMPLATE,
          predecessorTaskKey: td.pred,
          successorTaskKey: td.succ,
        } as Partial<ItsmChangeTemplateDependency> as ItsmChangeTemplateDependency);
        await tdRepo.save(existing);
        logAction('CREATED', 'TemplateDep', `${td.pred} -> ${td.succ}`);
        track('CREATED');
      } else {
        logAction('REUSED', 'TemplateDep', `${td.pred} -> ${td.succ}`);
        track('REUSED');
      }
    }

    // ── LAYER 4: Change Record ──
    console.log('LAYER 4: Seeding Change Record...');
    const chgRepo = ds.getRepository(ItsmChange);
    let change = await chgRepo.findOne({ where: { id: ID.CHANGE } });
    if (!change) {
      change = chgRepo.create({
        id: ID.CHANGE,
        tenantId: DEMO_TENANT_ID,
        number: 'CHG-TASK-DEMO-001',
        title: 'Database Platform Upgrade v15.4 — Task Orchestration Demo',
        description:
          'Upgrade the primary PostgreSQL database from v15.3 to v15.4. This change demonstrates task orchestration with parallel pre-checks, serial implementation steps, and parallel validation.',
        type: ChangeType.NORMAL,
        state: ChangeState.IMPLEMENT,
        risk: ChangeRisk.MEDIUM,
        approvalStatus: ChangeApprovalStatus.APPROVED,
        plannedStartDate: hoursAgo(2),
        plannedEndDate: new Date(NOW.getTime() + 4 * 60 * 60 * 1000),
        createdBy: DEMO_ADMIN_ID,
        isDeleted: false,
      } as Partial<ItsmChange> as ItsmChange);
      change = await chgRepo.save(change);
      logAction('CREATED', 'Change', change.title);
      track('CREATED');
    } else {
      logAction('REUSED', 'Change', change.title);
      track('REUSED');
    }

    // ── LAYER 5: Applied Tasks (from template) ──
    // Mixed states to demonstrate readiness:
    //   pre_check_1: COMPLETED  (done)
    //   pre_check_2: COMPLETED  (done)
    //   implement_1: IN_PROGRESS (ready, started — predecessors completed)
    //   implement_2: OPEN        (blocked — implement_1 not yet done)
    //   validate_1:  OPEN        (blocked — implement_2 not yet done)
    //   validate_2:  OPEN        (blocked — implement_2 not yet done)
    //   backout_prep: OPEN       (ready — pre_check_1 completed, non-blocking)
    console.log('LAYER 5: Seeding Applied Tasks (7) with mixed states...');
    const taskRepo = ds.getRepository(ItsmChangeTask);

    const appliedTasks = [
      {
        id: ID.TASK_PRE1,
        key: 'pre_check_1',
        title: 'Verify DB Backup Completed',
        type: ChangeTaskType.PRE_CHECK,
        status: ChangeTaskStatus.COMPLETED,
        seq: 0,
        sort: 0,
        stage: 'Pre-Flight',
        blocking: true,
        startAt: hoursAgo(2),
        endAt: hoursAgo(1.5),
      },
      {
        id: ID.TASK_PRE2,
        key: 'pre_check_2',
        title: 'Validate Rollback Script',
        type: ChangeTaskType.PRE_CHECK,
        status: ChangeTaskStatus.COMPLETED,
        seq: 1,
        sort: 1,
        stage: 'Pre-Flight',
        blocking: true,
        startAt: hoursAgo(2),
        endAt: hoursAgo(1.5),
      },
      {
        id: ID.TASK_IMPL1,
        key: 'implement_1',
        title: 'Run Database Migration',
        type: ChangeTaskType.IMPLEMENTATION,
        status: ChangeTaskStatus.IN_PROGRESS,
        seq: 2,
        sort: 2,
        stage: 'Execute',
        blocking: true,
        startAt: hoursAgo(1),
        endAt: null,
      },
      {
        id: ID.TASK_IMPL2,
        key: 'implement_2',
        title: 'Update Application Config',
        type: ChangeTaskType.IMPLEMENTATION,
        status: ChangeTaskStatus.OPEN,
        seq: 3,
        sort: 3,
        stage: 'Execute',
        blocking: true,
        startAt: null,
        endAt: null,
      },
      {
        id: ID.TASK_VAL1,
        key: 'validate_1',
        title: 'Run Integration Test Suite',
        type: ChangeTaskType.VALIDATION,
        status: ChangeTaskStatus.OPEN,
        seq: 4,
        sort: 4,
        stage: 'Validate',
        blocking: true,
        startAt: null,
        endAt: null,
      },
      {
        id: ID.TASK_VAL2,
        key: 'validate_2',
        title: 'Verify Monitoring Dashboards',
        type: ChangeTaskType.VALIDATION,
        status: ChangeTaskStatus.OPEN,
        seq: 5,
        sort: 5,
        stage: 'Validate',
        blocking: false,
        startAt: null,
        endAt: null,
      },
      {
        id: ID.TASK_BACKOUT,
        key: 'backout_prep',
        title: 'Prepare Backout Procedure',
        type: ChangeTaskType.BACKOUT,
        status: ChangeTaskStatus.OPEN,
        seq: 6,
        sort: 6,
        stage: 'Backout',
        blocking: false,
        startAt: null,
        endAt: null,
      },
    ];

    for (const t of appliedTasks) {
      let existing = await taskRepo.findOne({ where: { id: t.id } });
      if (!existing) {
        existing = taskRepo.create({
          id: t.id,
          tenantId: DEMO_TENANT_ID,
          changeId: ID.CHANGE,
          number: `CTASK${String(t.seq + 1).padStart(5, '0')}`,
          title: t.title,
          status: t.status,
          taskType: t.type,
          priority: ChangeTaskPriority.MEDIUM,
          sequenceOrder: t.seq,
          isBlocking: t.blocking,
          sortOrder: t.sort,
          stageLabel: t.stage,
          autoGenerated: true,
          sourceTemplateId: ID.TEMPLATE,
          templateTaskKey: t.key,
          actualStartAt: t.startAt,
          actualEndAt: t.endAt,
          createdBy: DEMO_ADMIN_ID,
          isDeleted: false,
        } as Partial<ItsmChangeTask> as ItsmChangeTask);
        await taskRepo.save(existing);
        logAction('CREATED', 'Task', `${t.title} [${t.status}]`);
        track('CREATED');
      } else {
        logAction('REUSED', 'Task', `${t.title} [${t.status}]`);
        track('REUSED');
      }
    }

    // ── LAYER 6: Applied Dependencies ──
    console.log('LAYER 6: Seeding Task Dependencies (6)...');
    const depRepo = ds.getRepository(ItsmChangeTaskDependency);

    const appliedDeps = [
      { id: ID.DEP_1, pred: ID.TASK_PRE1, succ: ID.TASK_IMPL1 },
      { id: ID.DEP_2, pred: ID.TASK_PRE2, succ: ID.TASK_IMPL1 },
      { id: ID.DEP_3, pred: ID.TASK_IMPL1, succ: ID.TASK_IMPL2 },
      { id: ID.DEP_4, pred: ID.TASK_IMPL2, succ: ID.TASK_VAL1 },
      { id: ID.DEP_5, pred: ID.TASK_IMPL2, succ: ID.TASK_VAL2 },
      { id: ID.DEP_6, pred: ID.TASK_PRE1, succ: ID.TASK_BACKOUT },
    ];

    for (const d of appliedDeps) {
      let existing = await depRepo.findOne({ where: { id: d.id } });
      if (!existing) {
        existing = depRepo.create({
          id: d.id,
          tenantId: DEMO_TENANT_ID,
          changeId: ID.CHANGE,
          predecessorTaskId: d.pred,
          successorTaskId: d.succ,
        } as Partial<ItsmChangeTaskDependency> as ItsmChangeTaskDependency);
        await depRepo.save(existing);
        logAction(
          'CREATED',
          'Dependency',
          `${d.pred.slice(-4)} -> ${d.succ.slice(-4)}`,
        );
        track('CREATED');
      } else {
        logAction(
          'REUSED',
          'Dependency',
          `${d.pred.slice(-4)} -> ${d.succ.slice(-4)}`,
        );
        track('REUSED');
      }
    }

    // ── Summary ──
    console.log('');
    console.log('='.repeat(70));
    console.log(
      `  SEED COMPLETE: ${stats.created} created, ${stats.reused} reused`,
    );
    console.log('');
    console.log('  DEMO DATA SUMMARY:');
    console.log('    Template: "Standard Deployment Pack" (STD_DEPLOY_V1)');
    console.log('      7 template tasks, 6 dependencies');
    console.log(
      '    Change: "Database Platform Upgrade v15.4" (CHG-TASK-DEMO-001)',
    );
    console.log('      7 applied tasks with traceability fields');
    console.log('      Mixed states: 2 COMPLETED, 1 IN_PROGRESS, 4 OPEN');
    console.log(
      '      Readiness: 2 ready (implement_1, backout_prep), 3 blocked',
    );
    console.log('      6 task dependencies (serial + parallel + optional)');
    console.log('');
    console.log('  DEPENDENCY GRAPH:');
    console.log('    pre_check_1 ──┐');
    console.log(
      '                  ├──> implement_1 ──> implement_2 ──┬──> validate_1',
    );
    console.log(
      '    pre_check_2 ──┘                                   └──> validate_2',
    );
    console.log('    pre_check_1 ──> backout_prep');
    console.log('');
    console.log('  READINESS STATE:');
    console.log('    pre_check_1:  COMPLETED (terminal)');
    console.log('    pre_check_2:  COMPLETED (terminal)');
    console.log('    implement_1:  IN_PROGRESS (ready: all predecessors done)');
    console.log('    implement_2:  OPEN (blocked: implement_1 not done)');
    console.log('    validate_1:   OPEN (blocked: implement_2 not done)');
    console.log('    validate_2:   OPEN (blocked: implement_2 not done)');
    console.log(
      '    backout_prep: OPEN (ready: pre_check_1 done, non-blocking)',
    );
    console.log('='.repeat(70));
  } finally {
    await app.close();
  }
}

seedChangeTaskDemo().catch((err: unknown) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
