import { Entity, Column, ManyToOne, JoinColumn, Index } from 'typeorm';
import { BaseEntity } from '../../../common/entities';
import { Tenant } from '../../../tenants/tenant.entity';
import { ItsmChange } from '../change.entity';

export enum ChangeTaskStatus {
  DRAFT = 'DRAFT',
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
  CANCELLED = 'CANCELLED',
}

export enum ChangeTaskType {
  IMPLEMENTATION = 'IMPLEMENTATION',
  VALIDATION = 'VALIDATION',
  BACKOUT = 'BACKOUT',
  PRE_CHECK = 'PRE_CHECK',
  REVIEW = 'REVIEW',
  APPROVAL_GATE = 'APPROVAL_GATE',
  OTHER = 'OTHER',
}

export enum ChangeTaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

@Entity('itsm_change_tasks')
@Index(['tenantId', 'changeId'])
@Index(['tenantId', 'changeId', 'number'], { unique: true })
@Index(['tenantId', 'status'])
@Index(['tenantId', 'assigneeId'])
@Index(['tenantId', 'assignmentGroupId'])
export class ItsmChangeTask extends BaseEntity {
  @ManyToOne(() => Tenant, { nullable: false })
  @JoinColumn({ name: 'tenant_id' })
  tenant: Tenant;

  @Column({ name: 'change_id', type: 'uuid' })
  changeId: string;

  @ManyToOne(() => ItsmChange, { nullable: false, onDelete: 'CASCADE' })
  @JoinColumn({ name: 'change_id' })
  change: ItsmChange;

  @Column({ type: 'varchar', length: 50 })
  number: string;

  @Column({ type: 'varchar', length: 255 })
  title: string;

  @Column({ type: 'text', nullable: true })
  description: string | null;

  @Column({
    type: 'varchar',
    length: 30,
    default: ChangeTaskStatus.DRAFT,
  })
  status: ChangeTaskStatus;

  @Column({
    name: 'task_type',
    type: 'varchar',
    length: 30,
    default: ChangeTaskType.OTHER,
  })
  taskType: ChangeTaskType;

  @Column({ name: 'assignment_group_id', type: 'uuid', nullable: true })
  assignmentGroupId: string | null;

  @Column({ name: 'assignee_id', type: 'uuid', nullable: true })
  assigneeId: string | null;

  @Column({
    type: 'varchar',
    length: 20,
    default: ChangeTaskPriority.MEDIUM,
  })
  priority: ChangeTaskPriority;

  @Column({ name: 'planned_start_at', type: 'timestamptz', nullable: true })
  plannedStartAt: Date | null;

  @Column({ name: 'planned_end_at', type: 'timestamptz', nullable: true })
  plannedEndAt: Date | null;

  @Column({ name: 'actual_start_at', type: 'timestamptz', nullable: true })
  actualStartAt: Date | null;

  @Column({ name: 'actual_end_at', type: 'timestamptz', nullable: true })
  actualEndAt: Date | null;

  @Column({ name: 'sequence_order', type: 'int', nullable: true })
  sequenceOrder: number | null;

  @Column({ name: 'is_blocking', type: 'boolean', default: true })
  isBlocking: boolean;

  @Column({ name: 'auto_generated', type: 'boolean', default: false })
  autoGenerated: boolean;

  @Column({ name: 'source_template_id', type: 'uuid', nullable: true })
  sourceTemplateId: string | null;

  @Column({ name: 'template_task_key', type: 'varchar', length: 100, nullable: true })
  templateTaskKey: string | null;

  @Column({ name: 'sort_order', type: 'int', default: 0 })
  sortOrder: number;

  @Column({ name: 'stage_label', type: 'varchar', length: 100, nullable: true })
  stageLabel: string | null;

  @Column({ type: 'text', nullable: true })
  notes: string | null;

  @Column({ name: 'estimated_duration_minutes', type: 'int', nullable: true })
  estimatedDurationMinutes: number | null;
}
