/**
 * ChangeTasksSection — Component Integration Tests
 *
 * Tests the ChangeTasksSection component with mocked API responses.
 * Covers:
 * - Empty state rendering
 * - Data render with tasks
 * - Create/edit interaction (mocked API)
 * - Template apply flow (mocked API)
 * - Quick status transition
 * - Blocked/readiness indicators
 * - Partial endpoint failure resilience (tasks OK, templates fail or vice versa)
 * - Envelope variants/null arrays safety
 *
 * @regression
 * @pr476
 */

import React from 'react';
import { render, screen, waitFor, fireEvent, within } from '@testing-library/react';
import '@testing-library/jest-dom';

// ---------------------------------------------------------------------------
// Mock grcClient before importing the component
// ---------------------------------------------------------------------------

const mockListTasks = jest.fn();
const mockGetTaskSummary = jest.fn();
const mockCreateTask = jest.fn();
const mockUpdateTask = jest.fn();
const mockDeleteTask = jest.fn();
const mockTemplateList = jest.fn();
const mockTemplateApply = jest.fn();

jest.mock('../../../services/grcClient', () => ({
  itsmApi: {
    changes: {
      listTasks: function() { return mockListTasks.apply(null, arguments); },
      getTaskSummary: function() { return mockGetTaskSummary.apply(null, arguments); },
      createTask: function() { return mockCreateTask.apply(null, arguments); },
      updateTask: function() { return mockUpdateTask.apply(null, arguments); },
      deleteTask: function() { return mockDeleteTask.apply(null, arguments); },
    },
    changeTemplates: {
      list: function() { return mockTemplateList.apply(null, arguments); },
      apply: function() { return mockTemplateApply.apply(null, arguments); },
    },
  },
}));

// Lazy-import component after mocks
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let ChangeTasksSection: any;
beforeAll(async () => {
  const mod = await import('../ChangeTasksSection');
  ChangeTasksSection = mod.ChangeTasksSection;
});

const CHANGE_ID = 'test-change-001';
const mockShowNotification = jest.fn();

const makeTask = (id: string, overrides?: Record<string, unknown>) => ({
  id,
  title: `Task ${id}`,
  description: 'Test task',
  status: 'OPEN',
  taskType: 'OTHER',
  priority: 'MEDIUM',
  sequenceOrder: 1,
  sortOrder: 1,
  isBlocking: false,
  autoGenerated: false,
  stageLabel: null,
  notes: null,
  estimatedDurationMinutes: null,
  plannedStartAt: null,
  plannedEndAt: null,
  readiness: null,
  number: null,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  ...overrides,
});

const makeSummary = (overrides?: Record<string, unknown>) => ({
  total: 0,
  readyCount: 0,
  blockedCount: 0,
  byStatus: {},
  byType: {},
  ...overrides,
});

describe('ChangeTasksSection — Component Tests', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    // Default: empty tasks, no summary
    mockListTasks.mockResolvedValue({ data: { data: [] } });
    mockGetTaskSummary.mockResolvedValue({ data: { data: makeSummary() } });
  });

  // ===========================================================================
  // Empty state
  // ===========================================================================
  describe('Empty state', () => {
    it('renders empty state when no tasks exist', async () => {
      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);
      
      await waitFor(() => {
        expect(screen.getByTestId('tasks-empty')).toBeInTheDocument();
      });
      expect(screen.getByText(/no tasks yet/i)).toBeInTheDocument();
    });

    it('renders "Add Task" and "Apply Template" buttons in empty state', async () => {
      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);
      
      await waitFor(() => {
        expect(screen.getByTestId('create-task-btn')).toBeInTheDocument();
      });
      expect(screen.getByTestId('apply-template-btn')).toBeInTheDocument();
    });
  });

  // ===========================================================================
  // Data render
  // ===========================================================================
  describe('Data render', () => {
    it('renders tasks in a table when tasks exist', async () => {
      mockListTasks.mockResolvedValue({
        data: { data: [makeTask('t1'), makeTask('t2', { title: 'Second Task' })] },
      });
      mockGetTaskSummary.mockResolvedValue({
        data: { data: makeSummary({ total: 2, byStatus: { OPEN: 2 } }) },
      });

      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(screen.getByTestId('tasks-table')).toBeInTheDocument();
      });
      expect(screen.getByText('Task t1')).toBeInTheDocument();
      expect(screen.getByText('Second Task')).toBeInTheDocument();
    });

    it('renders progress bar with correct percentage', async () => {
      mockListTasks.mockResolvedValue({
        data: { data: [makeTask('t1', { status: 'COMPLETED' }), makeTask('t2')] },
      });
      mockGetTaskSummary.mockResolvedValue({
        data: { data: makeSummary({ total: 2, byStatus: { COMPLETED: 1, OPEN: 1 } }) },
      });

      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(screen.getByText('50% complete')).toBeInTheDocument();
      });
    });

    it('shows readiness indicators (ready)', async () => {
      mockListTasks.mockResolvedValue({
        data: {
          data: [
            makeTask('t1', {
              readiness: { isReady: true, blockingPredecessors: [] },
            }),
          ],
        },
      });
      mockGetTaskSummary.mockResolvedValue({
        data: { data: makeSummary({ total: 1, readyCount: 1 }) },
      });

      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(screen.getByText('Ready')).toBeInTheDocument();
      });
    });

    it('shows readiness indicators (blocked)', async () => {
      mockListTasks.mockResolvedValue({
        data: {
          data: [
            makeTask('t1', {
              readiness: { isReady: false, blockingPredecessors: ['pred-1', 'pred-2'] },
            }),
          ],
        },
      });
      mockGetTaskSummary.mockResolvedValue({
        data: { data: makeSummary({ total: 1, blockedCount: 1 }) },
      });

      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(screen.getByText('Blocked (2)')).toBeInTheDocument();
      });
    });
  });

  // ===========================================================================
  // Create task interaction
  // ===========================================================================
  describe('Create task interaction', () => {
    it('opens create form when "Add Task" clicked', async () => {
      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(screen.getByTestId('create-task-btn')).toBeInTheDocument();
      });

      fireEvent.click(screen.getByTestId('create-task-btn'));

      await waitFor(() => {
        expect(screen.getByText(/create change task/i)).toBeInTheDocument();
      });
    });
  });

  // ===========================================================================
  // Partial endpoint failure resilience
  // ===========================================================================
  describe('Partial endpoint failure resilience', () => {
    it('renders tasks even when summary endpoint fails', async () => {
      mockListTasks.mockResolvedValue({
        data: { data: [makeTask('t1')] },
      });
      mockGetTaskSummary.mockRejectedValue({ response: { status: 500 } });

      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(screen.getByTestId('tasks-table')).toBeInTheDocument();
      });
      expect(screen.getByText('Task t1')).toBeInTheDocument();
    });

    it('shows error when tasks endpoint fails but summary succeeds', async () => {
      mockListTasks.mockRejectedValue({ response: { status: 500 } });
      mockGetTaskSummary.mockResolvedValue({
        data: { data: makeSummary({ total: 5 }) },
      });

      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(screen.getByTestId('tasks-error')).toBeInTheDocument();
      });
    });
  });

  // ===========================================================================
  // Envelope variants / null safety
  // ===========================================================================
  describe('Envelope variants / null safety', () => {
    it('handles { data: [...] } envelope', async () => {
      mockListTasks.mockResolvedValue({
        data: [makeTask('t-flat')],
      });
      mockGetTaskSummary.mockResolvedValue({ data: { data: makeSummary({ total: 1 }) } });

      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(screen.getByText('Task t-flat')).toBeInTheDocument();
      });
    });

    it('handles { data: { items: [...] } } paginated envelope', async () => {
      mockListTasks.mockResolvedValue({
        data: { data: { items: [makeTask('t-pag')], total: 1, page: 1, pageSize: 100 } },
      });
      mockGetTaskSummary.mockResolvedValue({ data: { data: makeSummary({ total: 1 }) } });

      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(screen.getByText('Task t-pag')).toBeInTheDocument();
      });
    });

    it('handles { items: [...] } flat paginated envelope', async () => {
      mockListTasks.mockResolvedValue({
        data: { items: [makeTask('t-items')], total: 1 },
      });
      mockGetTaskSummary.mockResolvedValue({ data: { data: makeSummary({ total: 1 }) } });

      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(screen.getByText('Task t-items')).toBeInTheDocument();
      });
    });

    it('handles null data gracefully', async () => {
      mockListTasks.mockResolvedValue({ data: null });
      mockGetTaskSummary.mockResolvedValue({ data: null });

      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(screen.getByTestId('tasks-empty')).toBeInTheDocument();
      });
    });

    it('handles { data: "string" } gracefully', async () => {
      mockListTasks.mockResolvedValue({ data: 'not-json' });
      mockGetTaskSummary.mockResolvedValue({ data: 'not-json' });

      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(screen.getByTestId('tasks-empty')).toBeInTheDocument();
      });
    });
  });

  // ===========================================================================
  // Template apply flow
  // ===========================================================================
  describe('Template apply flow', () => {
    it('opens template dialog when "Apply Template" clicked', async () => {
      mockTemplateList.mockResolvedValue({
        data: { data: [{ id: 'tmpl-1', name: 'Standard Template', isActive: true, taskCount: 3 }] },
      });

      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(screen.getByTestId('apply-template-btn')).toBeInTheDocument();
      });

      fireEvent.click(screen.getByTestId('apply-template-btn'));

      await waitFor(() => {
        expect(mockTemplateList).toHaveBeenCalled();
      });
    });
  });

  // ===========================================================================
  // Refresh behavior
  // ===========================================================================
  describe('Refresh behavior', () => {
    it('refresh button re-fetches tasks', async () => {
      render(<ChangeTasksSection changeId={CHANGE_ID} showNotification={mockShowNotification} />);

      await waitFor(() => {
        expect(mockListTasks).toHaveBeenCalledTimes(1);
      });

      fireEvent.click(screen.getByTestId('refresh-tasks-btn'));

      await waitFor(() => {
        expect(mockListTasks).toHaveBeenCalledTimes(2);
      });
    });
  });
});
